version: '3.5'

services:
  node1:
    container_name: node1
    image: cassandra
    ports: 
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
    restart: always
    volumes: 
      - "./volumes/cassandra-node1:/var/lib/cassandra"
    networks: 
      - cass

  node2:
    container_name: node2
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
    restart: always
    volumes: 
      - "./volumes/cassandra-node2:/var/lib/cassandra"
    depends_on: 
      - node1
    networks: 
      - cass

networks:
  cass: